### ISSUE TITLE
v1.1 exports empty text file

### ISSUE THREAD

**Issue by ararezaee** [Noxis-source/BG3-XP-Table-Generator#1]
![Untitled](https://github.com/Noxis-source/BG3-XP-Table-Generator/assets/24833434/df86d95b-4ecf-4f0f-bfca-ccfe62f609f3)

**Comment by 8BitCerberus** [comment]
Same issue. Left a bug report on the Nexus Mods page, but I'll copy/paste it here too, in case this is more convenient:

Tried generating a 2x XP / 1/2 XP per level and on export it crashes. It creates the [export folder]\Stats\Data\TreasureTable.txt and [export folder]\Stats\Data\Generated folder, but both the txt and folder are empty.

I'm able to recreate the crash every time I try exporting, whether MaxXP is set to 100,000 or 50,000 (for level 12 MaxLvl.) I've also tried both exporting into an existing folder that has data generated from the 1.0 release, and exporting into a new/empty folder, in case the 1.0 files were causing the issue. Also tried an export with the default linear curve generated XP, to see if it's because I was matching the BG3 curve (with level 1 being 0 XP), but it crashed on that as well.

I also checked if it crashes when saving to a local only folder (desktop), vs. a local cloud synced folder (mega and onedrive) with the same results.

**Comment by Noxis-source** [comment]
This one should nail it
https://github.com/Noxis-source/BG3-XP-Table-Generator/commit/90d15e9dde7e82498eb4cd2857fb3bcbfb41eca3

Let me know if it works now on your side

**Comment by 8BitCerberus** [comment]
That fixed it on my end, thank you!

**Comment by ararezaee** [comment]
Yep, it's working perfectly now, thanks.
I'll be closing the issue
